# Generated by Django 2.2.8 on 2019-12-06 09:09

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('tenant_domain', models.CharField(blank=True, max_length=256, unique=True)),
                ('sub_domain', models.CharField(blank=True, max_length=256, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
