# Generated by Django 2.2.8 on 2019-12-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_domain', models.CharField(max_length=256)),
                ('sub_domain', models.CharField(max_length=256)),
                ('verification_token', models.UUIDField()),
                ('admin_username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
            ],
        ),
    ]
